### ISSUE TITLE
Make the gaia pylon need kill gaia

### ISSUE THREAD

**Issue by yunling520** [sharkweekthings/plastek#6]
In the magic chapter of age 4，i found gaia pylon need alfsteel pylon and alfsteel pylon need alfsteel nugget ,but alfsteel ingot need mana-infuser and dragonstone .It means that i first need to kill gaia and enter alfheim ，then can make gaia pylon summon gaia.
v1.56     (From Google Translate), 

![2024-07-01_00-56-28](https://github.com/sharkweekthings/plastek/assets/58768174/8f930879-f592-4128-96ae-4015f8eaa7c2)
![2024-07-01_00-59-55](https://github.com/sharkweekthings/plastek/assets/58768174/74ce4a0e-39e0-4b1c-a19a-560896726713)
![2024-07-01_00-59-21](https://github.com/sharkweekthings/plastek/assets/58768174/dbc0b551-876f-4f2f-b50f-7610feea38dd)

**Comment by sharkweekthings** [comment]
Thank you for reporting this! It looks like this is just due to a misplaced datapack.  I'll get a hotfix build uploaded sometime before the end of the night, but if you want to fix it yourself in the mean time it's really easy.

there is a file "gaia_pylon.json" in this path: 
kubejs\data\botania\recipes

it should actually be placed here: 
kubejs\data\mythicbotany\recipes

This makes the requirement for the Gaia Pylon a "Mana Pylon" instead of the "Alfsteel Pylon".

**Comment by sharkweekthings** [comment]
should now be resolved with build v1.56.1

https://legacy.curseforge.com/minecraft/modpacks/plastek/files/5487247
